export default {
 whiskyList: [
    { "id":  2, "name": "Glenmorangie 10", "location": {"country": "Scotland", "region": "Highland"}, "age": 10, "state": "Opened", "price": "26" },
    { "id":  3, "name": "Nikka Miyagikyo", "location": {"country": "Japan"}, "age": 3, "state": "Opened", "price": "62.71" },
    { "id":  4, "name": "Suntory Yamazaki 12", "age": 12, "location": {"country": "Japan"}, "state": "Opened", "price": "83.29"},
    { "id":  5, "name": "Glenmorangie 18", "age": 18, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "71.21"},
    { "id":  6, "name": "Old Pulteney 17", "age": 17, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "76.80"},
    { "id":  7, "name": "Aberlour 18", "age": 18, "location": {"country": "Scotland", "region": "Speyside"}, "state": "Opened", "price": "133.16"},
    { "id":  8, "name": "Tamnavulin", "location": {"country": "Scotland", "region": "Speyside"}, "age": 3, "state": "Opened", "price": "22.50"},
    { "id":  9, "name": "Hazelburn 10", "age": 10, "location": {"country": "Scotland", "region": "Campbeltown"}, "age": 10, "state": "Opened", "price": "40"},
    { "id": 10, "name": "Glen Scotia 18", "age": 18, "location": {"country": "Scotland", "region": "Campbeltown"}, "state": "Opened", "price": "85.95"},
    { "id": 11, "name": "Caol Ila 12", "age": 12, "location": {"country": "Scotland", "region": "Islay"}, "state": "Opened", "price": "34.20"},
    { "id": 12, "name": "Lagavulin 16", "location": {"country": "Scotland", "region": "Islay"}, "age": 16, "state": "Opened", "price": "48.59"},
    { "id": 13, "name": "Springbank 15", "age": 15, "location": {"country": "Scotland", "region": "Campbeltown"}, "state": "Opened", "price": "52.20"},
    { "id": 14, "name": "Dalmore 18", "age": 18, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "112.50"},
    { "id": 15, "name": "Glenmorangie 10", "age": 10, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "25"},
    { "id": 16, "name": "Aberlour 12", "age": 12, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "38"},
    { "id": 17, "name": "GlenDronach 15 Revival", "age": 15, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "55.80"},
    { "id": 18, "name": "GlenDronach 18 Allardice", "age": 18, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "94.94"},
    { "id": 19, "name": "Oban 14", "age": 14, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "41.40"},
    { "id": 20, "name": "Glen Moray 15", "age": 15, "location": {"country": "Scotland", "region": "Speyside"}, "state": "Opened", "price": "48.75"},
    { "id": 21, "name": "Westland's Sherry Wood", "location": {"country": "USA"}, "age": 3, "state": "Opened", "price": "66.62"},
    { "id": 22, "name": "Westland's Sherry Wood", "location": {"country": "USA"}, "age": 3, "state": "Closed", "price": "66.62"},
    { "id": 23, "name": "GlenDronach 12 Original", "age": 12, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "41.95"},
    { "id": 24, "name": "GlenDronach 12 Original", "age": 12, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "41.95"},
    { "id": 25, "name": "GlenDronach 21 Parliament", "location": {"country": "Scotland", "region": "Highland"}, "age": 21, "state": "Closed", "price": "138"},
    { "id": 26, "name": "Suntory Yamazaki 12", "age": 12, "location": {"country": "Japan"}, "state": "Closed", "price": "120"},
    { "id": 27, "name": "Arran 10", "age": 10, "location": {"country": "Scotland", "region": "Highland"}, "state": "Opened", "price": "45"},
    { "id": 28, "name": "GlenDronach 15 Revival", "age": 15, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "64.99"},
    { "id": 29, "name": "Aberlour 10", "age": 10, "location": {"country": "Scotland", "region": "Speyside"}, "state": "Closed", "price": "25"},
    { "id": 30, "name": "Redbreast 12", "age": 12, "location": {"country": "Ireland"}, "state": "Opened", "price": "46"},
    { "id": 31, "name": "Arran 18", "age": 18, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "85"},
    { "id": 32, "name": "Glenmorangie 18", "age": 18, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "79.95"},
    { "id": 33, "name": "GlenDronach 18 Allardice", "age": 18, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "98.76"},
    { "id": 34, "name": "Old Pulteney 17", "age": 17, "location": {"country": "Scotland", "region": "Highland"}, "state": "Closed", "price": "99.95"},
    { "id": 35, "name": "BenRiach 12", "age": 12, "location": {"country": "Scotland", "region": "Speyside"}, "state": "Opened", "price": "45.90"},
    { "id": 36, "name": "Port Askaig 8", "location": {"country": "Scotland", "region": "Islay"}, "age": 8, "state": "Opened", "price": "46.50"},
  ]
};