export default {
  whiskyList: [
    {
      "id":  3, "name": "Nikka Miyagikyo", "age": 3, "location": "Japan", "state": "Opened", isScotch: false, "abv": 45,
      "description": "Miyagikyo Single Malt is described as soft and fruity.<br />Using less peaty malt, this whisky is distilled in a pot still heated by indirect steam at a low temperature. Miyagikyo Single Malt has an elegant fruitiness and a distinctive aroma with a strong Sherry cask influence.",
    },
    {
      "id":  4, "name": "Suntory Yamazaki 12", "age": 12, "location": "Japan", "state": "Opened", isScotch: false, "abv": 43,
      "appearance": "Pure gold",
      "nose": "Peach, pineapple, grapefruit, clove, candied orange, vanilla, Mizunara (Japanese oak)",
      "palate": "Coconut, cranberry, butter",
      "finish": "Sweet ginger, cinnamon, long finish",
      "description": "Succulent with soft fruit.",
    },
    {
      "id":  7, "name": "Aberlour 18", "age": 18, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 43,
      "appearance": "Auburn gold",
      "nose": "Rich and complex notes of toffee and butterscotch combine with ripe peach and bitter orange",
      "palate": "Perfect structure. Initial notes of soft apricot and cream are offset by developing flavours of blackcurrant jam and sweet oak with a touch of honey",
      "finish": "Very long and balanced, progresses from crème brûlée to a gentle oak flourish",
      "description": "The mature, deep, spicy one: a deeper Sherry influence adds more spiciness and a liquorice tang. Greater age adds body and develops the distinctive fruitiness to a rich raisin character.",
    },
    {
      "id":  8, "name": "Tamnavulin", "age": 3, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 40,
      "appearance": "Amber gold.",
      "nose": "Rich, warm aromas of apple, toffee and honey with sweet marzipan and subtle tangy marmalade notes.",
      "palate": "Fresh, mellow with pear creamy peaches and pineapple and a hint of Demerara sugar.",
      "finish": "Rich, smooth and refreshing. A signature Speyside malt.",
      "description": "Matured in American oak barrels for a sweet, mellow taste with a rich, smooth Sherry cask finish.",
    },
    {
      "id": 10, "name": "Glen Scotia 18", "age": 18, "location": "Campbeltown", "state": "Opened", isScotch: true, "abv": 46,
      "nose": "Crisp saltiness, perfumed floral notes and thick sweet toffee.",
      "palate": "Rich deep vanilla fruit flavours, apricot and pineapple, plump sultana.",
      "finish": "Long and dry with gentle warming spice.",
      "description": "An exceptional single malt whisky matured from specially selected casks that deliver the true character of a 18 year old Glen Scotia malt whisky.",
    },
    {
      "id": 11, "name": "Caol Ila 12", "age": 12, "location": "Islay", "state": "Opened", isScotch: true, "abv": 43,
      "appearance": "Pale straw.",
      "nose": "Subdued, citric fruitiness; a whiff of bath oil and dentist's mouthwash. A fresh and appetising nose, with little or no trace of smoke.",
      "palate": "Drinks well at natural strength; sweet start; pleasant, light fragrant smokiness and a lengthy finish.",
      "finish": "Sweet smokiness in the lingering, slightly sour finish.",
      "description": "Caol Ila 12 year old Single Malt Scotch Whisky is the colour of pale straw, with a delicate balance of tastes.",
    },
    {
      "id": 12, "name": "Lagavulin 16", "age": 16, "location": "Islay", "state": "Opened", isScotch: true, "abv": 43,
      "appearance": "Deep amber gold.",
      "nose": "Intensely flavoured, peat smoke with iodine and seaweed and a rich, deep sweetness.",
      "palate": "Dry peat smoke fills the palate with a gentle but strong sweetness, followed by sea and salt with touches of wood.",
      "finish": "A long, elegant peat-filled finish with lots of salt and seaweed.",
      "description": "Aged in oak casks for at least sixteen years, this much sought-after single malt has the massive peat-smoke that's typical of southern Islay - but also offering a dryness that turns it into a truly interesting dram.",
    },
    {
      "id": 13, "name": "Springbank 15", "age": 15, "location": "Campbeltown", "state": "Opened", isScotch: true, "abv": 46,
      "nose": "Demerara sugar, dark chocolate, Christmas cake, almonds, toffee, oak.",
      "palate": "Creamy, raisins, dark chocolate, figs, marzipan, brazil nuts and vanilla.",
      "finish": "Oak and sherry notes sustain and mingle with hints of leather.",
      "description": "Like a storm gathering off the Kintyre coast, our 15-year-old Springbank is dark and ominous, yet delicious. Best enjoyed after dinner or with your favourite cigar, this is a true classic.",
    },
    {
      "id": 14, "name": "Dalmore 18", "age": 18, "location": "Highland", "state": "Opened", isScotch: true, "abv": 43,
      "nose": "Vanilla, dark chocolate, orange and cinnamon",
      "palate": "Dark chocolate, candied citrus fruits, rich coffee, nutmeg and soft liquorice",
      "finish": "Citrus fruits and rich molasses",
      "description": "A magnificent whisky matured in American white oak ex-bourbon casks and aged Matusalem oloroso sherry casks.",
    },
    {
      "id": 15, "name": "Glenmorangie 10", "age": 10, "location": "Highland", "state": "Closed", isScotch: true, "abv": 40,
      "nose": "The scent of citrus and ripening peaches is softened by the aroma of vanilla.",
      "palate": "First, vanilla is detected on the tongue before it ripples along the palate bringing a burst of flowery fruitiness.",
      "finish": "About a minute after tasting, you are left with a clean and salving aftertaste with hints of orange and peach.",
      "description": "The original expression of our elegant, floral spirit and the real backbone of the Glenmorangie range. A ten-year-old single malt, Glenmorangie Original is produced by marrying the delicate spirit that emerges from Scotland's tallest stills, with first and second fill American white oak casks.<br />It is here, maturing for ten long years in a range of ex-bourbon casks such as our famous slow-grown and air-dried 'designer casks' from Missouri, that our raw spirit develops a perfect balance between sweetness and complexity. Resulting in a mature spirit that is soft, mellow and creamy. Perfect for enjoying at any time.",
    },
    {
      "id": 18, "name": "GlenDronach 18 Allardice", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 46,
      "appearance": "Bright deep gold with a tawny centre.",
      "nose": "Sweet aromatics of fudge and Muscovado sugar. Fruit compote and glacier morello cherries provide added complexity.",
      "palate": "Rich dark and seductive. Remarkable flavours of stewed fruits and all-spice marry together with classic aged Oloroso sherry and toasted walnut bread combined with chocolate orange.",
      "finish": "Tremendously complex and long.",
      "description": "The GlenDronach 18 years old has been named after the renowned founder of the distillery, James Allardice. This exceptional sherried single malt is non chill filtered and of natural colour. Matured in the finest Spanish Oloroso sherry casks and bottled at 46%, this sublime richly sherried malt is truly unforgettable.",
    },
    {
      "id": 19, "name": "Oban 14", "age": 14, "location": "Highland", "state": "Opened", isScotch: true, "abv": 43,
      "nose": "Fresh oranges, lemons, and pears, with a hint of salt and peat.",
      "palate": "Dried fig, spice, and a smoked malt dryness.",
      "finish": "Long, smooth, and oaky sweet with a grain of salt.",
      "description": "Flavours of orange peel, smoke, sea salt, and honey distinguish this full-bodied highland malt.",
    },
    {
      "id": 20, "name": "Glen Moray 15", "age": 15, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 40,
      "nose": "Sherried oak and butter toffee.",
      "palate": "Full-bodied and indulgently sweet. Imagine a spiced dark chocolate enjoyed with a finely oaked wine - intense and satisfying.",
      "finish": "Long and rich.",
      "description": "The amalgamation of two distinct cask styles - sherry and American oak. An exquisitely complex whisky with a hint of spice and delicate smoke that boasts heady dried fruits and rich dark chocolate.",
    },
    {
      "id": 21, "name": "Westland's Sherry Wood", "age": 3, "location": "USA", "state": "Opened", isScotch: false, "abv": 46,
      "nose": "Honey-dipped oatmeal raisin cookies, maple syrup, banana pancakes.",
      "palate": "Kiwi, maple syrup, raisins, sweet cookies, pastries, stewed yellow fruits.",
      "description": "While the practice of maturing whiskey in sherry casks isn’t as long-standing as peated whiskies, it has become a standard of old world sensibilities. We celebrate this custom by filling hogsheads and butts sourced from the same region the Scottish find their casks. But what we do with them differs. Again, our five-malt spirit plays a significant role, allowing us to balance the sherry influence with our local malted barley flavor. We have our sherry casks shipped whole, which is unusual in the business of whiskey. This provides a sherry character that is still incredibly vibrant in this whiskey, but we always ensure the barley notes have an equal voice, something rarely done in Scotland.",
    },
    {
      "id": 22, "name": "Westland's Sherry Wood", "age": 3, "location": "USA", "state": "Closed", isScotch: false, "abv": 46,
      "nose": "Honey-dipped oatmeal raisin cookies, maple syrup, banana pancakes.",
      "palate": "Kiwi, maple syrup, raisins, sweet cookies, pastries, stewed yellow fruits.",
      "description": "While the practice of maturing whiskey in sherry casks isn’t as long-standing as peated whiskies, it has become a standard of old world sensibilities. We celebrate this custom by filling hogsheads and butts sourced from the same region the Scottish find their casks. But what we do with them differs. Again, our five-malt spirit plays a significant role, allowing us to balance the sherry influence with our local malted barley flavor. We have our sherry casks shipped whole, which is unusual in the business of whiskey. This provides a sherry character that is still incredibly vibrant in this whiskey, but we always ensure the barley notes have an equal voice, something rarely done in Scotland.",
    },
    {
      "id": 23, "name": "GlenDronach 12 Original", "age": 12, "location": "Highland", "state": "Closed", isScotch: true, "abv": 43,
      "appearance": "Deep amber-red gold.",
      "nose": "Sweet, creamy vanilla, with hints of ginger. Spiced mulled wine and pear.",
      "palate": "Rich, creamy, silky-smooth. Warm, rich oak and sherry sweetness, full mouth feel, raisins and soft fruits. Spicy with medium length and a dry finish.",
      "finish": "Long, full and firm, slightly nutty.",
      "description": "This superb richly sherried single malt is matured for at least 12 years in a combination of the finest Spanish Pedro Ximenez and Oloroso sherry casks. Non-chill filtered, of natural colour and bottled at 43%, the GlenDronach 12 year old Original is a sweet, creamy dram.",
    },
    {
      "id": 24, "name": "GlenDronach 12 Original", "age": 12, "location": "Highland", "state": "Closed", isScotch: true, "abv": 43,
      "appearance": "Deep amber-red gold.",
      "nose": "Sweet, creamy vanilla, with hints of ginger. Spiced mulled wine and pear.",
      "palate": "Rich, creamy, silky-smooth. Warm, rich oak and sherry sweetness, full mouth feel, raisins and soft fruits. Spicy with medium length and a dry finish.",
      "finish": "Long, full and firm, slightly nutty.",
      "description": "This superb richly sherried single malt is matured for at least 12 years in a combination of the finest Spanish Pedro Ximenez and Oloroso sherry casks. Non-chill filtered, of natural colour and bottled at 43%, the GlenDronach 12 year old Original is a sweet, creamy dram.",
    },
    {
      "id": 25, "name": "GlenDronach 21 Parliament", "age": 21, "location": "Highland", "state": "Closed", isScotch: true, "abv": 48,
      "appearance": "Deep amber with a cherry wood sheen.",
      "nose": "A delicate mix of ripe autumnal fruits - notably blackberries and red plums. Rich Oloroso sherry and candied orange segments. Spiced oatmeal biscuits and toasted oak fragrances bring excellent weight and balance.",
      "palate": "Resolute flavours of fine Oloroso sherry and bitter chocolate sauce, which has been spread liberally over homemade plum pudding. This is all infused with fabulous spicy notes - cinnamon, allspice and nutmeg. Full bodied with smooth tannins.",
      "finish": "Long and lingering.",
      "description": "Matured in a combination of the finest Oloroso and Pedro Ximenez sherry casks for a minimum of 21 years, the ‘Parliament’ continues the great GlenDronach tradition of offering fruit-laden intensity in its single malts. This rich expression has been named ‘Parliament’ after the colony, or ‘parliament’, of rooks that have been nesting in the trees that overlook the GlenDronach distillery for almost 200 years. Bottled at 48%, the ‘Parliament’ is non chill filtered and of natural colour.",
    },
    {
      "id": 26, "name": "Suntory Yamazaki 12", "age": 12, "location": "Japan", "state": "Closed", isScotch: false, "abv": 43,
      "appearance": "Pure gold",
      "nose": "Peach, pineapple, grapefruit, clove, candied orange, vanilla, Mizunara (Japanese oak)",
      "palate": "Coconut, cranberry, butter",
      "finish": "Sweet ginger, cinnamon, long finish",
      "description": "Succulent with soft fruit.",
    },
    {
      "id": 27, "name": "Arran 10", "age": 10, "location": "Highland", "state": "Opened", isScotch: true, "abv": 46,
      "appearance": "Ripe Golden Barley",
      "nose": "The initial rush of rich vanilla sweetness gives way to a touch of cinnamon which adds a spicy edge to the soft and sweet texture. The classic Arran citrus notes have rounded with age and reveal new depths of character against a background of sweet oak.",
      "palate": "Sweetness, Apple, Citrus, Cinnamon.",
      "description": "The classic expression of Arran - our fresh and unique island style is captured beautifully in our 10 Year Old Single Malt. It is beautifully presented in a brand new pack and is most definitely your best introduction to Arran Single Malt.",
    },
    {
      "id": 28, "name": "GlenDronach 15 Revival", "age": 15, "location": "Highland", "state": "Closed", isScotch: true, "abv": 46,
      "appearance": "Antique Bronze.",
      "nose": "An intoxicating burst of maraschino cherry, ripe bramble and dark chocolate mint with hints of orange bitters and walnut liqueur.",
      "palate": "Honey-glazed apricot and ripe fig with a crescendo of black cherry, angelica and muscovado. Long and enveloping finish with dark manuka honey, herbal bitters and dark chocolate.",
      "description": "After ceasing production in 2015, The GlenDronach Revival Aged 15 years now returns to the core range  of the distillery’s line-up. The expression embodies The GlenDronach’s signature style of Spanish Sherry  Cask maturation in fine Pedro Ximénez and Oloroso sherry casks from Andalucía, quietly growing in stature for 15 years in the darkness of our dunnage warehouses.<br />In flavour, the expression offers sumptuous notes of dark fruits, rich chocolate and manuka honey with  an enveloping, memorable finish worthy of this monumental malt’s history. This luxuriously sherried Highland Single Malt Scotch Whisky is bottled at 46% ABV, non chill filtered and natural in colour.",
    },
    {
      "id": 29, "name": "Aberlour 10", "age": 10, "location": "Speyside", "state": "Closed", isScotch: true, "abv": 40,
    },
    {
      "id": 30, "name": "Redbreast 12", "age": 12, "location": "Ireland", "state": "Opened", isScotch: false, "abv": 40,
      "nose": "A complex spicy and fruity aroma with toasted wood notes evident.",
      "palate": "Full flavoured and complex; silky smooth with a harmonious balance of spicy, fruity, sherry and toasted notes.",
      "finish": "Satisfyingly long, the complex flavours linger on the palate.",
      "description": "Made from a mash of malted and unmalted barley and then triple distilled in copper pot stills, Redbreast 12 boasts the flavour complexity and distinctive qualities of Pot Still whiskey. Matured in a combination of Bourbon seasoned American Oak barrels and Oloroso Sherry seasoned Spanish oak butts, the distinctive Redbreast sherry style is a joy to behold in each and every bottle.",
    },
    {
      "id": 31, "name": "Arran 18", "age": 18, "location": "Highland", "state": "Opened", isScotch: true, "abv": 46,
      "appearance": "Deep amber",
      "nose": "Orchard fruits with syrup and toasted oak",
      "palate": "Sweetness, Spice, Citrus, Baked peaches.",
      "description": "The Arran 18 year-old is the one of the most popular expressions in our core range of single malts and an expression of which we are very proud",
    },
    {
      "id": 32, "name": "Glenmorangie 18", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 43,
      "nose": "Rich, rounded and sweet with dried fruits and a complex floral fragrance.",
      "palate": "The taste is balanced between honey, malt and flowery scents. Dates and figs emerge in the background with a hint of wood smoke.",
      "finish": "The finish is long and enticing with the sweetness of dried fruit and subtle dryness of Oloroso nuttiness.",
      "description": "The 18 Years Old is a single malt Scotch whisky of serious distinction. Once it has spent fifteen years maturing in American white oak casks approximately 30% is transferred into Spanish Oloroso casks to spend a further three years maturing. Then, when both elements have reached 18 years, we blend them back together to create a whisky with a rich bouquet and full, rounded flavour. For a whisky of this age this expression has maintained, thanks to our delicate floral spirit and fine Oloroso casks, an incredible degree of vibrancy where the raisiny sweetness of the sherry has been toned down by the nuttiness of the American oak.",
    },
    {
      "id": 33, "name": "GlenDronach 18 Allardice", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 46,
      "appearance": "Bright deep gold with a tawny centre.",
      "nose": "Sweet aromatics of fudge and Muscovado sugar. Fruit compote and glacier morello cherries provide added complexity.",
      "palate": "Rich dark and seductive. Remarkable flavours of stewed fruits and all-spice marry together with classic aged Oloroso sherry and toasted walnut bread combined with chocolate orange.",
      "finish": "Tremendously complex and long.",
      "description": "The GlenDronach 18 years old has been named after the renowned founder of the distillery, James Allardice. This exceptional sherried single malt is non chill filtered and of natural colour. Matured in the finest Spanish Oloroso sherry casks and bottled at 46%, this sublime richly sherried malt is truly unforgettable.",
    },
    {
      "id": 34, "name": "Old Pulteney 17", "age": 17, "location": "Highland", "state": "Closed", isScotch: true, "abv": 46,
      "appearance": "Red amber with a rich ochre hue.",
      "nose": "Sweet with traces of apples and pears: slightly woody with a hint of butterscotch.",
      "palate": "Sweet with soft fruits: kiwi, guava, peach.",
      "description": "Aged in both American and Spanish oak casks, the mid-range Old Pulteney 17 Year Old strikes the perfect balance between maturity and the distillery’s signature coastal style, winning hearts of whisky enthusiasts the world over.",
    },
    {
      "id": 35, "name": "BenRiach 12", "age": 12, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 46,
      "appearance": "Deep golden-bronze.",
      "nose": "Sherry cask maturation at its most fruity and luscious. Baked fruit salad with fig, pear, apricot and glacé cherry in mandarin syrup. Honey glazed flan with crème-caramel and toasted vanilla pod add to the multi-layered sweetness.",
      "palate": "A rich fruit cocktail of honeyed fig, baked pineapple and sultana fused with chocolate fondant and muscovado sugar, lifted by mandarin cream, ground nutmeg and vanilla. On the finish savour nectarine, candied grape and star anise, lingering into the dessert-like sherried finish.",
      "description": "At BenRiach Distillery we have developed a reputation for innovative maturation, using a diverse mix of cask types. This luscious 12 year old Single Malt Scotch Whisky is unconventionally made using three facets of sherry cask maturation: full sherry cask maturation, combined with Pedro Ximénez and Oloroso sherry cask finishing, for unexpected layers of fruit sweetness and toasted oak spice. Each facet of sherry cask maturation is expertly combined by our Master Blender to work in harmony, creating a luscious Single Malt Scotch Whisky with a multi- layered cocktail of fruit notes, further enriching BenRiach’s signature sweet, fruit-laden style.<br />Bottled at 46%, non-chill filtered and of natural colour.",
    },
    {
      "id": 36, "name": "Port Askaig 8", "age": 8, "location": "Islay", "state": "Opened", isScotch: true, "abv": 45.8,
      "description": "The perfect introduction to the Isle of Islay, Port Askaig 8 Year Old has a soft, sweet peaty character balanced to perfection. Ageing in refill American oak allows the character of the spirit to shine through, making for a gentle, smoky, moreish dram.",
    },
    {
      "id": 37, "name": "GlenDronach 15 Revival", "age": 15, "location": "Highland", "state": "Closed", isScotch: true, "abv": 46,
      "appearance": "Antique Bronze.",
      "nose": "An intoxicating burst of maraschino cherry, ripe bramble and dark chocolate mint with hints of orange bitters and walnut liqueur.",
      "palate": "Honey-glazed apricot and ripe fig with a crescendo of black cherry, angelica and muscovado. Long and enveloping finish with dark manuka honey, herbal bitters and dark chocolate.",
      "description": "After ceasing production in 2015, The GlenDronach Revival Aged 15 years now returns to the core range  of the distillery’s line-up. The expression embodies The GlenDronach’s signature style of Spanish Sherry  Cask maturation in fine Pedro Ximénez and Oloroso sherry casks from Andalucía, quietly growing in stature for 15 years in the darkness of our dunnage warehouses.<br />In flavour, the expression offers sumptuous notes of dark fruits, rich chocolate and manuka honey with  an enveloping, memorable finish worthy of this monumental malt’s history. This luxuriously sherried Highland Single Malt Scotch Whisky is bottled at 46% ABV, non chill filtered and natural in colour.",
    },
    {
      "id": 38, "name": "Redbreast 12", "age": 12, "location": "Ireland", "state": "Closed", isScotch: false, "abv": 40,
      "nose": "A complex spicy and fruity aroma with toasted wood notes evident.",
      "palate": "Full flavoured and complex; silky smooth with a harmonious balance of spicy, fruity, sherry and toasted notes.",
      "finish": "Satisfyingly long, the complex flavours linger on the palate.",
      "description": "Made from a mash of malted and unmalted barley and then triple distilled in copper pot stills, Redbreast 12 boasts the flavour complexity and distinctive qualities of Pot Still whiskey. Matured in a combination of Bourbon seasoned American Oak barrels and Oloroso Sherry seasoned Spanish oak butts, the distinctive Redbreast sherry style is a joy to behold in each and every bottle.",
    },
    {
      "id": 39, "name": "Suntory Yamazaki 12", "age": 12, "location": "Japan", "state": "Closed", isScotch: false, "abv": 43,
      "appearance": "Pure gold",
      "nose": "Peach, pineapple, grapefruit, clove, candied orange, vanilla, Mizunara (Japanese oak)",
      "palate": "Coconut, cranberry, butter",
      "finish": "Sweet ginger, cinnamon, long finish",
      "description": "Succulent with soft fruit.",
    },
    {
      "id": 40, "name": "GlenDronach 21 Parliament", "age": 21, "location": "Highland", "state": "Closed", isScotch: true, "abv": 48,
      "appearance": "Deep amber with a cherry wood sheen.",
      "nose": "A delicate mix of ripe autumnal fruits - notably blackberries and red plums. Rich Oloroso sherry and candied orange segments. Spiced oatmeal biscuits and toasted oak fragrances bring excellent weight and balance.",
      "palate": "Resolute flavours of fine Oloroso sherry and bitter chocolate sauce, which has been spread liberally over homemade plum pudding. This is all infused with fabulous spicy notes - cinnamon, allspice and nutmeg. Full bodied with smooth tannins.",
      "finish": "Long and lingering.",
      "description": "Matured in a combination of the finest Oloroso and Pedro Ximenez sherry casks for a minimum of 21 years, the ‘Parliament’ continues the great GlenDronach tradition of offering fruit-laden intensity in its single malts. This rich expression has been named ‘Parliament’ after the colony, or ‘parliament’, of rooks that have been nesting in the trees that overlook the GlenDronach distillery for almost 200 years. Bottled at 48%, the ‘Parliament’ is non chill filtered and of natural colour.",
    },
    {
      "id":  41, "name": "Hazelburn 10", "age": 10, "location": "Campbeltown", "state": "Closed", isScotch: true, "abv": 46,
      "nose": "Stewed pears and baked apples are followed by honeycomb and fudge notes.",
      "palate": "A lovely and rich whisky with vanilla and honey flavours, liquorice follows with a refreshing zestiness.",
      "finish": "A refined milk chocolate cream finish that is oily and chewy.",
      "description": "Rich in flavour, our Hazelburn 10-year-old is awash with scents and flavours that will delight.",
    },
    {
      "id":  42, "name": "Balvenie 15 Sherry Barrel", "age": 15, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 47.8,
      "nose": "Dried fruits overlaid with a gentle nuttiness.",
      "palate": "Rich with elegant oak and subtle spice.",
      "finish": "Long, sherried finish.",
      "description": "The Balvenie Single Barrel Sherry Cask has been matured exclusively in a single European oak sherry butt for at least 15 years. The term ‘Single Barrel’ conveys the unique nature of the single malt whisky, which has been drawn from a single cask of a single distillation.<br />Limited by nature, each heavily toasted European oak Oloroso sherry butt will yield no more than 800 bottles of Scotch whisky.",
    }
  ]
};
