export default {
 whiskyList: [
    {
      "id":  2, "name": "Glenmorangie 10", "age": 10, "location": "Highland", "state": "Opened", isScotch: true, "abv": 40,
      "appearance": "",
      "nose": "The scent of citrus and ripening peaches is softened by the aroma of vanilla.",
      "palate": "First, vanilla is detected on the tongue before it ripples along the palate bringing a burst of flowery fruitiness.",
      "finish": "About a minute after tasting, you are left with a clean and salving aftertaste with hints of orange and peach.",
      "description": "The original expression of our elegant, floral spirit and the real backbone of the Glenmorangie range. A ten-year-old single malt, Glenmorangie Original is produced by marrying the delicate spirit that emerges from Scotland's tallest stills, with first and second fill American white oak casks.<br />It is here, maturing for ten long years in a range of ex-bourbon casks such as our famous slow-grown and air-dried 'designer casks' from Missouri, that our raw spirit develops a perfect balance between sweetness and complexity. Resulting in a mature spirit that is soft, mellow and creamy. Perfect for enjoying at any time.",
    },
    {
      "id":  3, "name": "Nikka Miyagikyo", "age": 3, "location": "Japan", "state": "Opened", isScotch: false, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id":  4, "name": "Suntory Yamazaki 12", "age": 12, "location": "Japan", "state": "Opened", isScotch: false, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id":  5, "name": "Glenmorangie 18", "age": 18, "location": "Highland", "state": "Opened", isScotch: true, "abv": 43,
      "appearance": "",
      "nose": "Rich, rounded and sweet with dried fruits and a complex floral fragrance.",
      "palate": "The taste is balanced between honey, malt and flowery scents. Dates and figs emerge in the background with a hint of wood smoke.",
      "finish": "The finish is long and enticing with the sweetness of dried fruit and subtle dryness of Oloroso nuttiness.",
      "description": "The 18 Years Old is a single malt Scotch whisky of serious distinction. Once it has spent fifteen years maturing in American white oak casks approximately 30% is transferred into Spanish Oloroso casks to spend a further three years maturing. Then, when both elements have reached 18 years, we blend them back together to create a whisky with a rich bouquet and full, rounded flavour. For a whisky of this age this expression has maintained, thanks to our delicate floral spirit and fine Oloroso casks, an incredible degree of vibrancy where the raisiny sweetness of the sherry has been toned down by the nuttiness of the American oak.",
    },
    {
      "id":  6, "name": "Old Pulteney 17", "age": 17, "location": "Highland", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id":  7, "name": "Aberlour 18", "age": 18, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id":  8, "name": "Tamnavulin", "age": 3, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id":  9, "name": "Hazelburn 10", "age": 10, "location": "Campbeltown", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 10, "name": "Glen Scotia 18", "age": 18, "location": "Campbeltown", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 11, "name": "Caol Ila 12", "age": 12, "location": "Islay", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 12, "name": "Lagavulin 16", "age": 16, "location": "Islay", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 13, "name": "Springbank 15", "age": 15, "location": "Campbeltown", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 14, "name": "Dalmore 18", "age": 18, "location": "Highland", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 15, "name": "Glenmorangie 10", "age": 10, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 16, "name": "Aberlour 12", "age": 12, "location": "Highland", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 17, "name": "GlenDronach 15 Revival", "age": 15, "location": "Highland", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 18, "name": "GlenDronach 18 Allardice", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 19, "name": "Oban 14", "age": 14, "location": "Highland", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 20, "name": "Glen Moray 15", "age": 15, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 21, "name": "Westland's Sherry Wood", "age": 3, "location": "USA", "state": "Opened", isScotch: false, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 22, "name": "Westland's Sherry Wood", "age": 3, "location": "USA", "state": "Closed", isScotch: false, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 23, "name": "GlenDronach 12 Original", "age": 12, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 24, "name": "GlenDronach 12 Original", "age": 12, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 25, "name": "GlenDronach 21 Parliament", "age": 21, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 26, "name": "Suntory Yamazaki 12", "age": 12, "location": "Japan", "state": "Closed", isScotch: false, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 27, "name": "Arran 10", "age": 10, "location": "Highland", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 28, "name": "GlenDronach 15 Revival", "age": 15, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 29, "name": "Aberlour 10", "age": 10, "location": "Speyside", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 30, "name": "Redbreast 12", "age": 12, "location": "Ireland", "state": "Opened", isScotch: false, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 31, "name": "Arran 18", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 32, "name": "Glenmorangie 18", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 33, "name": "GlenDronach 18 Allardice", "age": 18, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 34, "name": "Old Pulteney 17", "age": 17, "location": "Highland", "state": "Closed", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 35, "name": "BenRiach 12", "age": 12, "location": "Speyside", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
    {
      "id": 36, "name": "Port Askaig 8", "age": 8, "location": "Islay", "state": "Opened", isScotch: true, "abv": 0,
      "appearance": "",
      "nose": "",
      "palate": "",
      "finish": "",
      "description": "",
    },
  ]
};